---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-rest-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: go-rest-api
  template:
    metadata:
      labels:
        name: go-rest-api
    spec:
      containers:
        - name: go-rest-api
          image: "dockerasu60/go-rest-api:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_PORT
              value: "5432"
            - name: DB_HOST
              value: "db"
            - name: DB_PASSWORD
              value: "6001"
            - name: DB_TABLE
              value: "postgres"
            - name: DB_USERNAME
              value: "postgres"